import Header from '@/components/Header';
import './globals.css';
import Footer from '@/components/Footer';
import { Roboto } from 'next/font/google';
import Providers from './providers';
import ScrolltoTop from '@/components/ScrolltoTop';
import Logo from './../public/logo.png';

const Robboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  openGraph: {
    title: 'Quran web Next.js',
    description: 'Generated by create next app',
    url: '<https://trihartono-quran.vercel.app/>',
    siteName: 'Next.js',
    images: [
      {
        url: './../public/Logo.png',
        width: 256,
        height: 256,
      },
    ],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${Robboto.className} px-setting relative"`}>
        <Providers>
          <Header />
          {children}
          <Footer />
          <ScrolltoTop />
        </Providers>
      </body>
    </html>
  );
}
