import Header from '@/components/Header';
import './globals.css';
import Footer from '@/components/Footer';
import { Roboto } from 'next/font/google';
import Providers from './providers';
import ScrolltoTop from '@/components/ScrolltoTop';
import Logo from './../public/logo256.png';

const Robboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Quran Web',
  description: 'Generated by create next app',
  image: [
    {
      url: Logo,
      width: 256,
      height: 257,
    },
  ],
  icons: {
    icon: { url: Logo, type: 'image/svg' },
    shortcut: { url: Logo, type: 'image/svg' },
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${Robboto.className} px-setting relative"`}>
        <Providers>
          <Header />
          {children}
          <Footer />
          <ScrolltoTop />
        </Providers>
      </body>
    </html>
  );
}
