'use client';
import Header from '@/components/Header';
import './globals.css';
import Footer from '@/components/Footer';
import { Roboto } from 'next/font/google';
import Providers from './providers';
import { HiArrowSmUp } from 'react-icons/hi';
const Robboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//The approach recommended by Next.js
const isBrowser = () => typeof window !== 'undefined';

function scrollToTop() {
  if (!isBrowser()) return;
  window.scrollTo({ top: 0, behavior: 'smooth' });
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${Robboto.className} px-setting relative"`}>
        <Providers>
          <Header />
          {children}
          <Footer />
          <div className="fixed bg-blue-400 rounded-full p-2 bottom-20 text-white right-4 z-20" onClick={scrollToTop}>
            <HiArrowSmUp className="w-5 h-5" />
          </div>
        </Providers>
      </body>
    </html>
  );
}
